apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
    spec:
      volumes:
      - name: cosi-secret
        secret:
          secretName: s3-credentials
      - name: logs
        emptyDir: {}
      initContainers:
      - name: logger
        image: alpine:3.21
        restartPolicy: Always
        command: ["sh"]
        args:
        - '-c'
        - |
          #!/bin/ash

          while true; do
              echo "$(date +'%Y-%m-%d %H:%M:%S') - Log entry" | tee -a "$LOG_FILE"

              # Check file size and trim if needed
              if [ -f "$LOG_FILE" ] && [ $(stat -c %s "$LOG_FILE") -gt $MAX_SIZE ]; then
                  echo "$(date +'%Y-%m-%d %H:%M:%S') - Rotating" | tee -a "$LOG_FILE.tmp"
                  mv "$LOG_FILE.tmp" "$LOG_FILE"
              fi

              sleep 10
          done
        env:
        - name: LOG_FILE
          value: /mnt/logs/log.txt
        - name: MAX_SIZE
          value: '4194304' # 4MB in bytes
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
        volumeMounts:
        - name: logs
          mountPath: /mnt/logs
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      containers:
      - name: uploader
        image: app
        args:
        - --upload-interval=240
        - --file=/mnt/logs/log.txt
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - name: logs
          mountPath: /mnt/logs
        - name: cosi-secret
          mountPath: /cosi
