apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: cosi-sample-
namespace: cosi-sample
resources:
- ../app
- ../cosi
images:
- name: app
  newName: localhost:5005/cosi-sample-app
  newTag: dev-6b754a-dirty
